- project:
    name: Juniper/contrail-infra
    check:
      jobs:
        - ci-test-mock-contrail-vnc-build-packages
        - contrail-build-containers-centos7-ocata:
            dependencies:
              - ci-test-mock-contrail-vnc-build-packages
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
              # contrail_version: '{{ packaging.version.public }}-latest'
        - contrail-build-test-containers:
            dependencies:
              - ci-test-mock-contrail-vnc-build-packages
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-build-containers-centos7-ocata:
            dependencies:
              - ci-test-mock-contrail-vnc-build-packages
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-build-containers-centos7-queens:
            dependencies:
              - ci-test-mock-contrail-vnc-build-packages
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-build-containers-centos7-rocky:
            voting: False
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-sanity-centos7-kolla-ocata:
            dependencies:
              - contrail-build-test-containers
              - contrail-build-containers-centos7-ocata
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-sanity-centos7-kolla-queens:
            dependencies:
              - contrail-build-test-containers
              - contrail-build-containers-centos7-queens
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-sanity-centos7-kolla-rocky:
            voting: False
            dependencies:
              - contrail-build-test-containers
              - contrail-build-containers-centos7-rocky
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
        - contrail-sanity-centos7-k8s:
            dependencies:
              - contrail-build-test-containers
              - contrail-build-containers-centos7-queens
            vars:
              contrail_package_repository: 'http://ci-nexus.englab.juniper.net/repository/yum-tungsten-nightly/master-538-centos'
              setup_docker_registry: false
    gate:
      jobs:
        - puppet-lint
